Добавлен комментарий предупреждения.
Grisha-OK/Github-for-me- pull request #13
Opened 2021-01-05 16:13 UTC by Grisha-OK

Добавлен комментарий предупреждения о том что Data_base_extras ломает базу банных.
resolved #9

2021-01-05 16:36 UTC, solonrome requested changes
Смотри комментарий по коду.
https://github.com/Grisha-OK/Github-for-me-/pull/13/files

2021-01-05 16:36 UTC, solonrome commented on Data_base_extras.py
> +Если фаил data_base_file.json, то скрипт Data_base_extras.py ламает фаил data_base_file.json
Если файл data_base_file.json что?
Тут важнее написать инструкцию как правильно пользоваться этим скриптом. А уж потом предупредить о последствиях.

2021-01-07 09:58 UTC, Grisha-OK commented
https://github.com/Grisha-OK/Github-for-me-/pull/13/commits/d5a540a7726a60badf4becd2027f950d1d1892a2
Исправил.
@solonrome

2021-01-07 10:06 UTC, solonrome approved these changes

2021-01-07 10:06 UTC, merged