Добавлено логирование операций: в transaction.log
Grisha-OK/Github-for-me- pull request #21
Opened 2021-01-21 14:21 UTC by Grisha-OK

Добавлено однострочное логирование операций: в файл transaction.log
resolved #4

2021-01-21 16:05 UTC, solonrome requested changes

2021-01-21 16:05 UTC, solonrome commented on Swiss_bank.py
> +    calendar_date = str(year) + "-" + str(month)  + "-" + str(numeric) + " " + str(hour) + ":" + str(menute)
Тут можно сильно упростить - сделав шаблон прямо в тайме:
calendar_date=time.strftime("%Y-%m-%d %H:%M")

2021-01-21 16:05 UTC, solonrome commented on Swiss_bank.py
> +    log_stor = str(calendar_date) + " Операции: " + str(type_of_transaction) + " Номер счета: " + str(account_number_for_logging) + "," + " Что было: " + str(what_happened) + "," + " Что изменилось:
Составные строки гораздо удобнее собирать не на плюсиках, а помощью string.format или f-строк.
https://python-scripts.com/f-strings

2021-01-21 16:05 UTC, solonrome commented on Swiss_bank.py
> +    data_logging("Монепуляцыя со счотом", account_number_input, account_balance , account_balance_input)
Тут тип операции напрашивается "дебет" и "кредит" в зависимости от знака +-.
И пробегись по орфографии, для логов это важно.

2021-01-21 16:05 UTC, solonrome commented on Swiss_bank.py
> +    before_edit_message = s + " " + n + " " + d
Лог пишется даже если операция была отменена

2021-01-22 09:13 UTC, Grisha-OK commented
Так, ну вроде всё что ты озвучил я поправил.

2021-01-22 11:19 UTC, solonrome approved these changes

2021-01-22 11:20 UTC, merged